name: CI

on:
  pull_request:

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pre-commit
      - name: Install frontend dependencies
        run: |
          cd frontend
          npm install
      - name: Run pre-commit
        run: pre-commit run --all-files --show-diff-on-failure
      - name: Run Python tests
        run: pytest -q
      - name: Run frontend tests
        run: |
          cd frontend
          npm test --silent
